// single-spa/vue-single-spa/landing/src/components/Grid.vue
<template>
<div>
  <div class="container">Get your best animal icon</div>
  <div class="grid">
    <div v-for="animal in animals" :key='animal.name' class="grid-item" @click="openInfo(animal)">
      <div>{{ animal.name }}</div>
      <img :src="animal.img" :alt="animal.name" class="grid-img">
    </div>
  </div>
</div>
  
</template>

<script>
import { animals } from '../data';

export default {
  name: 'Grid',
  data() {
    return {
      animals: animals
    }
  },
  methods: {
     openInfo(animal) {
      this.$router.push({ path: '/icons', query: { id: animal.id } })
    }
  }
  
}
</script>

<style>
.container {
  padding-top: 20px;
  display: flex;
  justify-content: center;
  font-weight: bold
}

.grid {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  grid-template-rows: 100px;
  grid-gap: 20px;
  padding: 15px;
  justify-items: center;
  align-items: center
}

.grid-img {
  height: 35px;
}

.grid-item {
  display: flex;
  flex-direction: column;
  cursor: pointer;
}
</style>

// single-spa/react-single-spa/landing/src/Grid.tsx
import { animals } from '../src/data.js';
import { useNavigate  } from "react-router-dom";

export const Grid = () => {
  let navigate = useNavigate();

  const showDetailt = ({ id }) => {
    navigate(`/icons/?${id}`);
  }

  const style = {
    display: 'grid',
    'grid-template-columns': '1fr 1fr 1fr',
    'grid-template-rows': '100px',
    'grid-gap': '20px',
    'padding': '15px',
    'justify-items': 'center',
    'align-items': 'center'
  }

  const grid = animals.map((animal, i) => {
    return (
      <div key={i} onClick={() => showDetailt(animal)} style={{ cursor: 'pointer'}}>
        <div>{animal.name}</div>
        <div>{animal.decs}</div>
        <img src={animal.img} alt={animal.name} style={{ height: '50px' }}></img>
      </div>
    )
  })
  return (
    <div style={style}>{grid}</div>
  )
}
